version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies"
      - rm -rf node_modules
      - rm package-lock.json
      - npm cache clean --force
      - npm install
  build:
    commands:
      - echo "Building the app"
      - npm run build
  post_build:
    commands:
      - echo "Done building the app"

artifacts:
  base-directory: dist
  files:
    - '**/*'
