version: 0.2

phases:
  pre_build:
    commands:
      - ls -la
      - pwd
      - echo "Installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the app"
      - npm run build
  post_build:
    commands:
      - echo "Removing node_modules"
      - rm -rf node_modules/
artifacts:
  base-directory: dist
  files:
    - '**/*'
